### ISSUE TITLE
Cascading stack config parameters overwrites the entire parameter section

### ISSUE THREAD

**Issue by dragonraid** [cloudreach/sceptre#464]
Hello,
I have following config directory structure.

```
config/
    env/
        config.yaml
        vpc.yml [first_level]
        ou1/
             vpc.yaml [second_level]
```

In both vpc.yaml files I am referencing the same cf template and have `parameters` section. My intended use is to overwrite some of the parameters from `vpc.yaml [first_level]` in `vpc.yaml [second_level]` 

Here is the example of my config:

`vpc.yaml [first_level]`
```
template_path: templates/NetworkingAndContentDelivery/VPC/vpc.yaml
parameters:
  SharedValue: value
  EnvName: foo
```

`vpc.yaml [second_level]`
```
template_path: templates/NetworkingAndContentDelivery/VPC/vpc.yaml
parameters:
  EnvName: bar
```

However when I try to launch the environment:

```
sceptre --var-file=varfile.yaml launch-env env # varfile.yaml is for config.yaml
```

I hit the following error:

```
botocore.exceptions.ClientError: An error occurred (ValidationError) when calling the CreateStack operation: Parameters: [SharedValue] must have values
```

Looks like the `vpc.yaml [second_level]` overwrites the entire `parameters` section instead of individual parameters.

I think this is a bug and parameters should be overwritten individually

**Comment by ngfgrant** [comment]
Hey @dragonraid can you just confirm which version of sceptre you are using. This should have been fixed in >v1.4

**Comment by dragonraid** [comment]
Hi @ngfgrant,
I was originally trying with version `1.4.0`. Today I tried with `1.4.1` and I am still getting the same behaviour.

**Comment by ngfgrant** [comment]
Ah yes, that is the intended behaviour - i.e child-wins - for attributes of stack config except for dependencies (dependencies get merged rather than overwritten. 

The changes introduced in v1.4 let you specify in the code which merge method you want to adopt. So in order to change this behaviour, you probably want to change the code base in `config.py` https://github.com/cloudreach/sceptre/blob/v1/sceptre/config.py#L30

You can view the current strategies here: https://github.com/cloudreach/sceptre/blob/v1/sceptre/strategies.py

If you want to add a new strategy then please feel free to open up a PR. I am away for a couple of weeks. Hope that helps point you in the right direction.

**Comment by dragonraid** [comment]
`dict_merge` strategy was what I was looking for, but I think, that original implementation, does not work as intended. 

Function https://github.com/cloudreach/sceptre/blob/v1/sceptre/strategies.py#L26 does not return merged dicts (as I believe is intended), but operation result, which is in successful case, is `None`.

IMO Correct implementation should be:
```
if b is not None:
     a.update(b)
     return a
```

With this change I was able to use sceptre for my usecase.

**Comment by schlomo** [comment]
Maybe https://github.com/Scout24/yamlreader can help? It has tests and deals with complex merging issues of YAML structures (Disclaimer: I am the original author).
