### ISSUE TITLE
Cross Account resolver issues

### ISSUE THREAD

**Issue by sopeters** [cloudreach/sceptre#727]

**Comment by sopeters** [comment]
I have read https://github.com/cloudreach/sceptre/issues/257 and trying to use cross-account resolver in 2.1.3. 

I understand this is only possible with stack_output_external (and use of profiles) and not stack_output?

My setup is Account A runs sceptre under profile_A credentials and tried to reference outputs from Account B.

config of A/exampleA.yaml
`parameterX: !stack_output_external <exampleB> <profile_B>`

it seems the lookup happens in the same account I run sceptre on (Account A) and not in Account B. getting 

> Stack with id other-account-stackname does not exist

If I reference a stack on the same account (A) it works which leads me to the assumption that the profile / role change to profile_B isn't working.

Stackgroup Config for Account A (A/config.yaml):
profile: profile_A

Stackgroup Config for Account B (B/config/yaml):
profile: profile_B

Anything I'm doing wrong here? Anything else I can do to debug more?

**Comment by sopeters** [comment]
I have also tried A/exampleA.yaml

`parameterX:  !stack_output <exampleB>::<var>`

directly as https://github.com/cloudreach/sceptre/commit/bf70aec9f88e095d295c93a40d091d4d45f57b3e suggests this is supported 

Getting `exampleB - Stack is in the PENDING state`

Seems it looks in AccountA for StackB and creates it wrongly

**Comment by ngfgrant** [comment]
@sopeters qq. Do you have any AWS environment variables set?

**Comment by sopeters** [comment]
Hi @ngfgrant - I tried both options. Would be nice to have AWS environment setup from the CI/CD tools in secrets (otherwise I would have to set AWS keys in my source code and check this into the repo -> big NO). With the AWS environment variables set I run into the error

`An error occurred (AccessDenied) when calling the CreateStack operation: Cross-account pass role is not allowed` 

I assume this is the role_arn for the ExecutionRole I have in place for CF operations (in the A/config.yaml and B/config.yaml)

Without AWS environment variables I get the result that the dependent stack (stack B) is described with the correct account / role (I can see the boto3 session created)
...
then the Stack A is used by the correct account with

`[2019-06-08 12:15:44] - exampleA - Stack is in the CREATE_COMPLETE state
[2019-06-08 12:15:44] - exampleA - Updating Stack
[2019-06-08 12:15:44] - Resolving Stack output: B/exampleB.yaml::<var>
[2019-06-08 12:15:44] - Collecting outputs from 'exampleB'...
[2019-06-08 12:15:44] - No cloudformation client found, creating one...
[2019-06-08 12:15:44] - Getting Boto3 session
Stack with id exampleB does not exist`

Still seems its trying to find a StacK B in Account A again.

**Comment by cornerman** [comment]
@sopeters That is a bug I have also encountered. Please check out this PR: https://github.com/cloudreach/sceptre/pull/726. It should fix it. You can try it out by installing `pip install git+https://github.com/cornerman/sceptre@stack-outputs`

**Comment by sopeters** [comment]
Thanks @cornerman - that's it for the bug. Hope it gets merged in the next version.

---

Still having the issue that for the boto3 session environment variables take higher priorities over profile and changing roles via source_profile is failing. Once the AWS_ACCESS_KEY_ID, etc are set the profile on session generation isn't used and cross account via profiles in ~/.aws/config access fails. 

My ~/.aws/config looks like:

[profile profileA]
region = ap-southeast-2
role_arn = arn:aws:iam::1234567890:role/CloudFormationAdminRole
source_profile = master_user

[profile profileB]
region = ap-southeast-2
role_arn = arn:aws:iam::1234567891:role/CloudFormationAdminRole
source_profile = master_user

I now need to set the credentials (AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY) for the master_user in the shell. 

One workaround could be to set no environment variables for that and specify all account specific AWS credentials in ~/.aws/credentials - I have a few accounts so that's cumbersome.

Another one could be to change the ConnectionManager to set config for Session creation to ensure not to pass AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY and AWS_SESSION_TOKEN if a profile has been passed in?

I might be missing something here or is there any easier solution?

**Comment by cornerman** [comment]
> Another one could be to change the ConnectionManager to set config for Session creation to ensure not to pass AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY and AWS_SESSION_TOKEN if a profile has been passed in?

That is actually an interesting idea! We could probably shield the connection manager against credentials outside of the profile. When you specify a profile for a stack group in sceptre, you really want to use that profile. The b could lead to searious issues when doing it by mistake and in your case it is cumbersome.

For me, I am exclusively managing my account with `AWS_PROFILE`, so I never came accross this problem. But then there might come a time where this hits you as a surprise :owl:

**Comment by sopeters** [comment]
Thanks @cornerman - are you able to share an example how you manage this with 'AWS_PROFILE' ?

I had a play with changing Connection Manager too. It could do something like 

>                if profile is not None:
>
>                config = {
>                    "region_name": region,
>                   "profile_name": profile
>                }
>                else:
>                config = {
>                   "region_name": region,
>                    "aws_access_key_id": environ.get("AWS_ACCESS_KEY_ID"),
>                    "aws_secret_access_key": environ.get("AWS_SECRET_ACCESS_KEY"),
>                    "aws_session_token": environ.get("AWS_SESSION_TOKEN")
>                }

Works but not sure if that would lead to other issues...?!

**Comment by cornerman** [comment]
> Thanks @cornerman - are you able to share an example how you manage this with 'AWS_PROFILE' ?

Your profile example looked good to me! I just meant profiles, not specifically using `AWS_PROFILE`. In my spectre deployment I only use the profile from the stack-group config, not an environment variable.

I also have different profiles for referencing different accounts. In my setup I have some global resources that are always deployed into a specific account and other resources that are deployed to different accounts (depending on the deployment variables). In sceptre, I reference these profiles in the stack-groups and up until now they just worked.

So my structure looks kind of like this:
```
config/
  global/
    config.yaml --> profile: Account1
    A.yaml
  dynamic/
   config.yaml --> profile: Account2
   B.yaml
   global/
      config.yaml --> profile: Account1
      Allow-B-To-A.yaml --> policies to allow access from B in Account1 to A in Account2

```

There are some minor annoyances like, you cannot deploy `dynamic/B.yaml` alone, eventhough it would spin up `globa/A.yaml` as a dependency, it would not pull `Allow-B-To-A.yaml`. You would need launch that explicitly or alway launch the whole stack-group `dynamic` (which is what I do).

Does that help?

**Comment by sopeters** [comment]
Thanks - that helps. It's similar to my setup then.
